name: CICD

on:
  push:
    branches: [ main ]
    
jobs:
  check_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: dotnet build  
          
  deploy:
    needs: [check_build]
    name: Deploy to VPS
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Push to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ~/TelegramBot_Observer/
            git pull
            dotnet build
            dotnet run
